### ISSUE TITLE
SAML认证BUG,spring官方的例子spring-boot-security-saml-sample认证不成功

### ISSUE THREAD

**Issue by ricardo0624** [MaxKeyTop/MaxKey#36]
如何复现
1. https://github.com/vdenotaris/spring-boot-security-saml-sample 这是spring官方的例子,可以自己跑跑试试
2. 自己解析的我用的是saml-client,非常简单,你们也可以写个demo试试

还有smal配置,加密的配置,你们根本没有使用,所以证书是必填的选项,但是你们表单没有设成必填,所以这也是个坑

**Comment by shimingxy** [comment]
当前对接阿里云和腾讯云都是正常的，你说的问题我们详细问题所在，在下一个版本会有结果

**Comment by ricardo0624** [comment]
![2020-11-13_18-13](https://user-images.githubusercontent.com/12064877/99061545-b256d500-25dc-11eb-9069-72e6ece42f02.png)
我自己写的解析,这是你们服务器报的错误
![size](https://user-images.githubusercontent.com/12064877/99061577-c13d8780-25dc-11eb-8fe2-25541673f1f1.png)
如果服务器不报错误,返回的内容依然不正确,我这边报的错误

**Comment by ricardo0624** [comment]
https://gitee.com/david0624/demo-simple-saml
这是我自己写的demo,非常简单,samlcontroller,一个是request,一个是response,而且证书什么的,resouces里面已经提供好了,很方便你们测试,辛苦了,开源不易

**Comment by ricardo0624** [comment]
不知道什么时候能修复,我司正好用到这块,现在再集成

**Comment by shimingxy** [comment]
感谢你对我们的关注，该问题已经在下个版本的计划中了，最晚预计12月底完成修复并和v2.4.0GA一同发布

**Comment by shimingxy** [comment]
如果很急的话建议可以使用其他协议

**Comment by shimingxy** [comment]
问题详细描述：
先是依赖错误,noClassdefError,然后又是其它错误,然后我自己写的解析,请求可以到登陆页了,结果要么服务器报错,要么返回的报文不合法,总之就是不能用

**Comment by shimingxy** [comment]
修复

**Comment by ricardo0624** [comment]
你们用我写的demo测试了吗

**Comment by ricardo0624** [comment]
还有bug的关闭,我觉得客户验证以后,在关闭也不持,我这里现在直接500 internel error,而且后台没有任何错误,我觉得这一点也不科学

**Comment by shimingxy** [comment]
把springboot调整了一下，请见https://github.com/MaxKeyTop/spring-boot-security-saml-sample------------------ 原始邮件 ------------------发件人: David.Lee.Ricardo  <notifications@github.com>发送时间: 2020年11月27日 17:02收件人: MaxKeyTop/MaxKey <MaxKey@noreply.github.com>抄送: MaxKey <shimingxy@163.com>, State change <state_change@noreply.github.com>主题: 回复：[MaxKeyTop/MaxKey] SAML认证BUG,spring官方的例子spring-boot-security-saml-sample认证不成功 (#36)
你们用我写的demo测试了吗

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/MaxKeyTop/MaxKey/issues/36#issuecomment-734725511",
"url": "https://github.com/MaxKeyTop/MaxKey/issues/36#issuecomment-734725511",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ricardo0624** [comment]
我给了两个例子，一个是spring security saml的，一个是saml client的，我们没用spring security，所一用的saml client，还是不行，这个我也给了demo的

**Comment by shimingxy** [comment]
请下载最新代码和sql，用我们提供的基于java版本的springboot的官方例子https://github.com/MaxKeyTop/spring-boot-security-saml-sample------------------ 原始邮件 ------------------发件人: David.Lee.Ricardo  <notifications@github.com>发送时间: 2020年11月29日 17:58收件人: MaxKeyTop/MaxKey <MaxKey@noreply.github.com>抄送: MaxKey <shimingxy@163.com>, State change <state_change@noreply.github.com>主题: 回复：[MaxKeyTop/MaxKey] SAML认证BUG,spring官方的例子spring-boot-security-saml-sample认证不成功 (#36)
我给了两个例子，一个是spring security saml的，一个是saml client的，我们没用spring security，所一用的saml client，还是不行，这个我也给了demo的

—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/MaxKeyTop/MaxKey/issues/36#issuecomment-735368943",
"url": "https://github.com/MaxKeyTop/MaxKey/issues/36#issuecomment-735368943",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
